# Site settings
title: Hacker jeff
email: wew@wew.com
url: https://hackerjef.github.io
description: "I'm a admin on Many servers and a programer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Hacker Jeff

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/august4577
  - title: steam
    url: http://steamcommunity.com/id/Hackerjeff/
  - title: youtube
    url: https://www.youtube.com/august4577
  - title: github
    url: https://github.com/Hackerjef
  - title: paypal
    url: https://www.paypal.me/Auguststenz

# Build settings
markdown: kramdown
permalink: pretty
